<?php

function manageProduct() {
    #RECEBE OS VALORES DIGITADOS NO FORMULÁRIO DE PRODUTO E COLOCA ELES EM VARIÁVEIS
    #VERIFICA SE O ID DO PRODUTO JÁ EXISTE
        #CASO EXISTA, A FUNÇÃO UPDATE PRODUCT SERÁ CHAMADA CONTENDO OS DADOS COMO PARAMETROS
        #SENÃO, A FUNÇÃO ADD PRODUCT SERÁ CHAMADA CONTENDO OS DADOS COMO PARAMETROS
}

function addProduct() {
    #CRIA UM CÓDIGO SQL PARA ADICIONAR OS VALORES DOS PARAMETROS A TABELA NO BANCO DE DADOS
    #UTILIZA O QUERY PARA EXECUTAR O CÓDIGO ARMAZENANDO NA VARIÁVEL RESULT
    #REDIRECIONA PARA A LISTA DE PRODUTOS
}

function listProducts() {
    #CRIA UM CÓDIGO SQL PARA SELECIONAR TODAS AS LINHAS DA TABELA
    #UTILIZA O QUERY PARA EXECUTAR O CÓDIGO ARMAZENANDO NA VARIÁVEL RESULT
    #VERIFICA SE ALGUM RESULTADO É RETORNADO DA VARIÁVEL RESULT
    #RETORNA UM ARRAY COM AS INFORMAÇÕES DO RESULTADO
}

function updateProduct() {
    #CRIA UM CÓDIGO SQL PARA ATUALIZAR A TABELA COM OS VALORES DOS PARAMETROS ONDE O ID FOR IGUAL AO PARAMETRO ID
    #UTILIZA O QUERY PARA EXECUTAR O CÓDIGO ARMAZENANDO NA VARIÁVEL RESULT
    #REDIRECIONA PARA A LISTA DE PRODUTOS
}

function deleteProduct() {
    #BUSCA O ID DO PRODUTO CUJO O BOTÃO REMOVER FOI CLICADO
    #ARMAZENA ESSE ID EM UMA VARIÁVEL
    #CRIA UM CÓDIGO SQL PARA DELETAR A LINHA DO PRODUTO PELO ID
    #UTILIZA O QUERY PARA EXECUTAR O CÓDIGO ARMAZENANDO NA VARIÁVEL RESULT
}