<?php

function catalogProduct() {
    #CRIA UM CÓDIGO SQL PARA SELECIONAR TODAS AS LINHAS DA TABELA EM UMA ORDEM ALEATÓRIA
    #UTILIZA O QUERY PARA EXECUTAR O CÓDIGO ARMAZENANDO NA VARIÁVEL RESULT
    #VERIFICA SE ALGUM RESULTADO É RETORNADO DA VARIÁVEL RESULT
    #CHAMA A FUNÇÃO QUERY PRODUCT COM O PARAMETRO RESULT
}

function searchProduct() {
    #RECEBE O VALOR DIGITADO NA BARRA DE PESQUISA E COLOCA ELE EM UMA VARIÁVEL
    #CRIA UM CÓDIGO SQL PARA SELECIONAR TODAS AS LINHAS NA QUAL O VARIÁVEL ESTÁ PRESENTE
    #UTILIZA O QUERY PARA EXECUTAR O CÓDIGO ARMAZENANDO NA VARIÁVEL RESULT
    #CHAMA A FUNÇÃO QUERY PRODUCT COM O PARAMETRO RESULT
}

function queryProduct() {
    #VERIFICA SE ALGUM RESULTADO É RETORNADO DO PARAMETRO RESULT
    #RETORNA UM ARRAY COM AS INFORMAÇÕES DO RESULTADO
}