<?php

    function getCart() {
        #INICIA UMA SESSÃO
        #VERIFICA SE EXISTE ALGUM ID DE USUÁRIO NA SESSÃO
        #CRIA UM CÓDIGO SQL PARA SELECIONAR A LINHA DO CARRINHO PELO ID DO USUÁRIO
        #UTILIZA O QUERY PARA EXECUTAR O CÓDIGO ARMAZENANDO NA VARIÁVEL RESULT
        #VERIFICA SE ALGUM RESULTADO É RETORNADO DA VARIÁVEL RESULT
            #CASO TENHA UM RETORNO, UM ARRAY MULTIDIMENSIONAL SERÁ CRIADO COM OS DADOS PRESENTES NO ARRAY MULTIDIMENSIONAL DA TABELA
            #CASO NÃO TENHA UM RETORNO, UM ARRAY MULTIDIMENSIONAL SERÁ CRIADO SEM DADOS
    }

    function addCart() {
        #BUSCA O ID DO PRODUTO CUJO O BOTÃO ADICIONAR FOI CLICADO
        #ARMAZENA ESSE ID EM UMA VARIÁVEL
        #CRIA UM CÓDIGO SQL PARA SELECIONAR A LINHA DO PRODUTO PELO ID
        #UTILIZA O QUERY PARA EXECUTAR O CÓDIGO ARMAZENANDO NA VARIÁVEL RESULT
        #VERIFICA SE O ID DO PRODUTO NÃO EXISTE NO ARRAY MULTIDIMENSIONAL
            #CASO NÃO EXISTA, OS DADOS SERÃO ADICIONADOS AO ARRAY
    }

    function listCart() {
        #EXECUTA A FUNÇÃO GET CART
        #RETORNA TODOS OS ARRAYS DENTRO DO ARRAY MULTIDIMENSIONAL
        #CASO NÃO HAJA NENHUM ARRAY DENTRO DO ARRAY MULTIDIMENSIONAL, ELE IRÁ RETORNAR APENAS UM ECHO
    }

    function checkout() {
        #RECEBE OS DADOS DE CHECKOUT, INCLUINDO O ID DO PRODUTO
        #ARMAZENA ESSE ID EM UMA VARIÁVEL
        #CRIA UM CÓDIGO SQL PARA ALTERAR O VALOR DA QUANTIDADE DO PRODUTO PELO VALOR DA QUANTIDADE DENTRO DO ARRAY MULTIDIMENSIONAL
        #CASO A QUANTIDADE SEJA MENOR DO QUE 1, O SITE RETORNARÁ A MENSAGEM FALHA AO COMPRAR, PRODUTO FORA DE ESTOQUE
        #UTILIZA O QUERY PARA EXECUTAR O CÓDIGO ARMAZENANDO NA VARIÁVEL RESULT
        #EXECUTA A FUNÇÃO REMOVE CART
    }
    
    function removeCart() {
        #BUSCA O ID DO PRODUTO CUJO O BOTÃO REMOVER FOI CLICADO
        #ARMAZENA ESSE ID EM UMA VARIÁVEL
        #REMOVE O ARRAY CUJO O ID PERTENCE DO ARRAY MULTIDIMENSIONAL
    }